Repository codestates/just-moment-trip, pull requests merged in 2022-05, with the labels that each got.

#342 안쓰는 import문 삭제
  server/controllers/diary/index.js
Labels: Refectoring 🔧, 🐜 Project - α

#343 fix : 쓸모없는 주석 삭제
  server/config/config.js
  server/controllers/diary/levenshtein-distance.js
  server/migrations/20220408012133-create-user.js
  server/models/account.js
  server/models/trip.js
  server/models/user.js
Labels: 🐜 Project - α

#349 리액트 password 는 form 태그 안에 감싸져있어야한다
  client/src/components/MyPage/UpdateModal.js
  client/src/pages/Mypage.js
Labels: 🐜 Project - α

#350 feat:로컬스토리지를 새션스토리지로 바꿈
  client/src/components/Account/AccountStore.js
  client/src/components/Diary/DiaryStore.js
  client/src/components/Trip/triplist.js
  client/src/modules/Reducers/userReducer.js
  client/src/services/headers.js
  client/src/services/sign.js
Labels: 🐜 Project - α

#351 Fix : Token
  client/src/components/Trip/triplist.js
  client/src/services/trip.js
Labels: 🐜 Project - α

#353 Fix : console 주석처리 및 수정
  client/src/components/Diary/DiaryEditor.js
  client/src/components/Diary/DiaryStore.js
  client/src/components/Diary/DiaryWriteUp.js
  client/src/pages/Account.js
  client/src/pages/Diary.js
  client/src/services/accout.js
Labels: ■■■■□, FrontEnd🌖, Fix 🛠, 🐜 Project - α

#355 사진 새로고침해야만 적용되는거 수정
  client/src/components/MyPage/InfoButton.js
  client/src/components/Picture/Pic.js
Labels: Fix 🛠, 🐜 Project - α

#356 S3 파일 삭제 안되던거 해결함
  client/src/components/MyPage/InfoButton.js
  client/src/components/Picture/Pic.js
Labels: Fix 🛠, 🐜 Project - α

#359 FIX : console.log & 이스터에그
  client/src/components/Account/AccountStore.js
  client/src/components/Diary/DiaryEditor.js
  client/src/components/Diary/DiaryWriteUp.js
  client/src/components/Trip/triplist.js
  client/src/components/common/HashTag.js
  client/src/pages/Home.js
Labels: BUG🦠, FrontEnd🌖, Fix 🛠, 🐜 Project - α

#371 마이페이지
  client/src/components/MyPage/InfoButton.js
  client/src/components/MyPage/UpdateModal.js
  client/src/services/diary.js
  client/src/services/sign.js
  server/controllers/user/index.js
  server/controllers/user/sign.js
Labels: Fix 🛠, 🐜 Project - α

#374 FIX : Trip 작성 시, 빈 공란이 하나라도 있을 경우 submit을 하지 못하도록 함
  client/src/components/Trip/textfield.js
  client/src/components/Trip/tripmodal.js
Labels: ASAP⚡️, FrontEnd🌖, Refectoring 🔧, Fix 🛠, 🐜 Project - α

#375 가입할시 중복 이메일 거르는 작업
  client/src/components/SignUp/Input.js
  client/src/modules/Reducers/userReducer.js
  client/src/services/sign.js
Labels: Fix 🛠, 🐜 Project - α

#380 회원탈퇴시 제대로 작동하지 않던거 고침
  client/src/components/MyPage/InfoButton.js
Labels: BUG🦠, Fix 🛠, 🐜 Project - α

#382 LoginMessage와 TripMessage 겹치는게 많아서 합쳐줌
  client/src/components/common/LoginTripMessage.js
  client/src/components/common/NoTrip.js
  client/src/pages/Account.js
  client/src/pages/Diary.js
  client/src/pages/Mypage.js
  client/src/pages/Trip.js
Labels: Refectoring 🔧, 🐜 Project - α

#383 트립 입구컷 에러
  client/src/components/Trip/tripmodal.js
  client/src/pages/Account.js
  client/src/pages/Diary.js
Labels: Fix 🛠, 🐜 Project - α

#384 feat:sign up할때 클라이언트와 서버 통신간의 RSA적용
  client/src/services/sign.js
  server/config/config.js
  server/controllers/user/RSA.js
  server/controllers/user/sign.js
  server/migrations/20220408012133-create-user.js
  server/models/user.js
Labels: 🐜 Project - α

#388 FIX : Account & Diary 코드수정
  client/src/components/Account/AccountStore.js
  client/src/components/Diary/DiaryStore.js
  client/src/components/Trip/tripmodal.js
  client/src/components/common/HashTag.js
Labels: BUG🦠, FrontEnd🌖, Refectoring 🔧, Fix 🛠, 🐜 Project - α
