Repository codestates/just-moment-trip, pull requests merged in 2022-06, with the labels that each got.

#397 feat: RSA signIn에도 적용
  client/src/services/sign.js
  client/src/services/trip.js
  server/controllers/user/RSA.js
  server/controllers/user/sign.js
  server/controllers/user/test.js
Labels: 🐜 Project - α

#398 비밀번호 수정에 RSA 추가함
  client/src/components/MyPage/InfoButton.js
  server/controllers/user/index.js
Labels: Feature🙌, 🐜 Project - α

#401 fix : 비밀번호 특수문자 입력 불가 고침
  client/src/components/SignUp/Input.js
  client/src/components/SingIn/Input.js
Labels: 🐜 Project - α

#406 Feat : Code Spliting
  client/package-lock.json
  client/package.json
  client/src/components/Diary/DiaryStore.js
  client/src/components/Diary/DiaryWriteUp.js
  client/src/routers/index.js
Labels: ASAP⚡️, Feature🙌, FrontEnd🌖, 🐜 Project - α

#410 feat:카이사르와 모노알파벳암호화를 rsa적용전에 추가 함. 로그인,회원가입,비번변경 모두 적용 완료
  client/jsconfig.json
  client/package-lock.json
  client/package.json
  client/src/components/Diary/DiaryList.js
  client/src/components/MyPage/InfoButton.js
  client/src/services/caesar_monoAlphabet.js
  client/src/services/sign.js
  client/webpack.config.dev.js
  client/webpack.config.prod.js
  server/controllers/user/caesar_monoAlphabet.js
  server/controllers/user/index.js
  server/controllers/user/sign.js
  server/controllers/user/test.js
  server/index.js
Labels: 🐜 Project - α

#411 fix:카이사르 암호와 shiftnum이 26이상어어도 가능하게, 특수문자는 쉬프팅 안되 게 업그레이드
  client/src/services/caesar_monoAlphabet.js
  server/controllers/user/caesar_monoAlphabet.js
Labels: 🐜 Project - α

#412 fix:비밀번호수정 해싱횟수변경
  server/controllers/user/index.js
Labels: 🐜 Project - α

#416 Feat : 로딩창구현
  client/package-lock.json
  client/package.json
  client/src/components/Account/AccountList.js
  client/src/components/Account/AccountStore.js
  client/src/components/Diary/DiaryList.js
  client/src/components/Diary/DiaryStore.js
  client/src/components/Diary/DiaryWriteUp.js
  client/src/components/common/Loding.js
Labels: ASAP⚡️, Feature🙌, Merge👏, FrontEnd🌖, 🐜 Project - α

#418 feat:소수데이터 생성 및 배포자동화 진행중
  appspec.yml
  scripts/initialize.sh
  scripts/start.sh
  scripts/stop.sh
  server/controllers/user/RSA.js
  server/controllers/user/index.js
  server/controllers/user/primeData.js
Labels: 🐜 Project - α

#420 fix : loading component
  client/src/Assets/babies.jpg
  client/src/components/common/Loding.js
Labels: ASAP⚡️, Fix 🛠, 🐜 Project - α

#425 fix : trip
  client/src/components/Trip/textfield.js
  client/src/components/Trip/tripmodal.js
Labels: ASAP⚡️, FrontEnd🌖, Fix 🛠, 🐜 Project - α

#428 FIX : Account
  client/src/components/Account/AccountList.js
  client/src/components/Account/AccountStore.js
  client/src/components/Account/AccountWriteUp.js
Labels: ASAP⚡️, FrontEnd🌖, Fix 🛠, 🐜 Project - α

#430 feat : 가계부 그래프에 원도 적용
  client/src/components/Account/AccountPieChart.js
Labels: 🐜 Project - α

#431 fix : account
  client/src/components/Account/AccountEditor.js
  client/src/components/Account/AccountList.js
  client/src/components/Account/AccountStore.js
  client/src/components/Account/AccountWriteUp.js
  client/src/services/account.js
Labels: FrontEnd🌖, Fix 🛠, 🐜 Project - α

#435 feat:비밀번호 찾기
  client/src/components/Account/AccountList.js
  server/controllers/user/caesar_monoAlphabet.js
  server/controllers/user/nodemaile.js
  server/controllers/user/sign.js
  server/controllers/user/test.js
  server/package-lock.json
  server/package.json
  server/routes/sign.js
  server/routes/user.js
Labels: 🐜 Project - α

#436 fix : trip
  client/src/components/Account/AccountList.js
  client/src/components/Account/AccountStore.js
  client/src/components/Trip/trip.js
  client/src/components/Trip/triplist.js
Labels: ASAP⚡️, FrontEnd🌖, Fix 🛠, 🐜 Project - α

#437 feat:회원가입 이메일 인증 만드 는중...
  client/src/services/sign.js
  server/controllers/user/sign.js
  server/routes/sign.js
Labels: 🐜 Project - α

#438 비밀번호 찾기 클라이언트 버튼 구현
  client/src/components/SingIn/Input.js
  client/src/components/SingIn/PassFindModal.js
  client/src/services/sign.js
Labels: Feature🙌, FrontEnd🌖, 🐜 Project - α

#441 fix : Footer 수정
  client/src/components/Account/AccountList.js
  client/src/components/Account/AccountPieChart.js
  client/src/components/Account/AccountStore.js
  client/src/components/common/Footer.js
Labels: ASAP⚡️, Feature🙌, FrontEnd🌖, Fix 🛠, 🐜 Project - α

#445 feat:메일내에 프로젝트레포로가는 링크 추가
  server/controllers/user/nodemaile.js
Labels: 🐜 Project - α

#447 FIX : CSS
  client/src/components/Trip/trip.js
  client/src/components/Trip/triplist.js
Labels: BUG🦠, ASAP⚡️, FrontEnd🌖, CSS 🎨, Fix 🛠, 🐜 Project - α

#448 Feat : Top Button 구현
  client/src/components/Account/AccountList.js
  client/src/components/Diary/DiaryList.js
  client/src/components/Trip/trip.js
  client/src/components/common/TopBtn.js
Labels: ASAP⚡️, Component📦, Feature🙌, FrontEnd🌖, 挑战成功 🐣, 🐜 Project - α

#449 FIX : Home CSS
  client/src/pages/Home.js
Labels: BUG🦠, CSS 🎨, 🐜 Project - α

#451 간단한 수정
  client/src/components/Account/AccountList.js
  client/src/components/Account/Map.js
  client/src/components/Diary/DiaryList.js
  client/src/components/Diary/DiaryWriteUp.js
  client/src/components/Info/AccountInfo.js
  client/src/components/Info/Container.js
  client/src/components/Info/DiaryInfo.js
  client/src/components/Info/GraphInfo.js
  client/src/components/Info/TripInfo.js
  client/src/components/SignUp/Input.js
  client/src/components/Trip/textfield.js
  client/src/components/Trip/triplist.js
  client/src/components/Trip/tripmodal.js
  client/src/components/common/Loading.js
  client/src/services/sign.js
  client/src/services/trip.js
Labels: Fix 🛠, 🐜 Project - α

#453 feat : 인증코드 스케쥴러통한 제거, 새코드 발급시 이전 코드 제거, 특수문자 오류 제거
  server/controllers/user/sign.js
  server/controllers/user/signup_delete_schedule.js
  server/index.js
Labels: 🐜 Project - α

#456 s3 이미지 업로드할때 숨겨야할 값 숨김
  client/src/components/Picture/Pic.js
Labels: Fix 🛠, 🐜 Project - α

#457 환경변수 사용하는곳 한곳 더 추가함
  client/src/components/MyPage/UserInfo.js
Labels: Fix 🛠, 🐜 Project - α

#458 FIX : Account date
  client/src/components/Account/AccountEditor.js
  client/src/components/Account/AccountList.js
  client/src/components/Account/AccountStore.js
  client/src/components/Diary/DiaryList.js
  client/src/components/Trip/triplist.js
  client/src/components/common/Loading.js
  client/src/services/account.js
Labels: BUG🦠, FrontEnd🌖, Fix 🛠, 🐜 Project - α

#460 서버 수정 및 추가
  server/controllers/account/index.js
  server/controllers/trip/index.js
  server/routes/trip.js
Labels: Feature🙌, BackEnd🌒, Fix 🛠, 🐜 Project - α

#462 ADD : PICS / FIX : Account
  client/src/Assets/amongus.gif
  client/src/Assets/parrot13.gif
  client/src/components/Diary/DiaryEditor.js
  client/src/components/Trip/trip.js
  client/src/components/Trip/tripeditor.js
  client/src/components/Trip/triplist.js
  client/src/services/trip.js
Labels: Feature🙌, FrontEnd🌖, Fix 🛠, 🐜 Project - α

#463 FINISH : TRIP
  client/src/components/Account/AccountStore.js
  client/src/components/Trip/trip.js
  client/src/components/Trip/tripeditor.js
  client/src/components/Trip/triplist.js
  client/src/components/Trip/tripmodal.js
  client/src/services/trip.js
Labels: ASAP⚡️, FrontEnd🌖, 挑战 🥚, 挑战成功 🐣, Fix 🛠, 🐜 Project - α

#464 카카오로그인
  client/src/components/MyPage/InfoButton.js
  client/src/services/sign.js
  server/controllers/oauth/index.js
Labels: BackEnd🌒, Fix 🛠, 🐜 Project - α

#465 카카오로그인 수정
  server/controllers/oauth/index.js
Labels: Fix 🛠, 🐜 Project - α

#466 fix : 카카오로그인 수정완료
  server/controllers/oauth/caesar_monoAlphabet.js
  server/controllers/oauth/index.js
Labels: BackEnd🌒, 🐜 Project - α

#468 FIX : CSS
  client/src/Assets/amongus.gif
  client/src/Assets/jammanbo.gif
  client/src/Assets/meu.gif
  client/src/Assets/parrot13.gif
  client/src/components/Account/AccountList.js
  client/src/components/Diary/DiaryList.js
  client/src/components/Trip/tripeditor.js
  client/src/components/Trip/triplist.js
  client/src/components/common/Loading.js
Labels: ASAP⚡️, FrontEnd🌖, CSS 🎨, Fix 🛠, 🐜 Project - α

#469 해시태그 순서대로 저장하기
  client/src/components/Diary/DiaryList.js
  server/controllers/diary/index.js
Labels: BackEnd🌒, Fix 🛠, 🐜 Project - α

#471 fix : 지도 전체 보는 아이콘 삭제 후 각 카드별로 전체 보게끔
  client/src/components/Account/AccountEditor.js
  client/src/components/Account/AccountList.js
  client/src/components/Account/Map.js
  client/src/components/Account/MultipleMap.js
  client/src/components/Account/MyVerticallyCenteredModal.js
Labels: 🐜 Project - α

#475 다이어리 검색 리렌더링 이슈 해결
  client/src/components/Account/MyVerticallyCenteredModal.js
  client/src/components/Diary/DiaryList.js
  client/src/components/Diary/DiaryStore.js
Labels: FrontEnd🌖, 🐜 Project - α

#478 어카운트 다이어리 날짜정렬 및 안쓰는 import문들 삭제
  client/src/components/Account/AccountList.js
  client/src/components/Account/AccountStore.js
  client/src/components/Diary/DiaryStore.js
  client/src/components/Info/AccountInfo.js
  client/src/components/Info/asdfasdf.gif
  client/src/components/Trip/tripeditor.js
  client/src/components/Trip/triplist.js
  client/src/components/common/Footer.js
  client/src/services/account.js
  client/src/services/diary.js
Labels: Fix 🛠, 🐜 Project - α

#479 다이어리 날짜별 데이터추출 수정
  client/src/components/Diary/DiaryList.js
  client/src/components/Trip/tripeditor.js
  client/src/components/Trip/triplist.js
  client/src/services/sign.js
  client/src/services/trip.js
Labels: Fix 🛠, 🐜 Project - α

#482 feat:comment 기본 틀
  server/controllers/account/index.js
  server/controllers/postRequest/comment.js
  server/controllers/postRequest/post.js
  server/index.js
  server/migrations/20220620061908-create-comment.js
  server/models/comment.js
  server/routes/comment.js
  server/routes/post.js
Labels: 🐜 Project - α

#483 feat : 게시글
  server/controllers/postRequest/post.js
  server/index.js
  server/migrations/20220620074141-create-post.js
  server/migrations/20220620074718-fk-post.js
  server/models/index.js
  server/models/post.js
  server/routes/comment.js
  server/routes/post.js
Labels: BackEnd🌒, 🐜 Project - α

#485 게시글 오류 잡고 완성
  server/controllers/postRequest/post.js
  server/migrations/20220620074718-fk-post.js
  server/models/index.js
Labels: BackEnd🌒, Fix 🛠, 🐜 Project - α

#490 Making Post List
  client/package-lock.json
  client/package.json
  client/src/components/Post/Pagination.js
  client/src/components/Post/PostItem.js
  client/src/components/Post/PostList.js
  client/src/components/Post/PostList.jsx
  client/src/components/Post/PostStore.js
  client/src/components/Post/PostStore.jsx
  client/src/components/Post/dummydata.js
  client/src/components/Post/styles.js
  client/src/components/Post/styles.jsx
  client/src/pages/Post.js
Labels: Component📦, Feature🙌, Mission Complete✌️, 도움요청!🤷‍♂️, FrontEnd🌖, Build Up ⛏, CSS 🎨, 🐜 Project - α

#492 FIX : SighUp & Post
  client/src/components/Post/PostItem.js
  client/src/components/Post/PostList.js
  client/src/components/Post/styles.js
  client/src/components/SignUp/Input.js
Labels: ASAP⚡️, Feature🙌, FrontEnd🌖, Fix 🛠, 🐜 Project - α

#496 feat:클라쪽 comment
  client/src/services/comment.js
  server/controllers/postRequest/comment.js
  server/controllers/postRequest/post.js
  server/migrations/20220620061908-create-comment.js
  server/migrations/20220620074718-fk-post.js
  server/migrations/20220620160912-fk-comment.js
  server/models/comment.js
  server/models/index.js
  server/routes/comment.js
Labels: 🐜 Project - α

#497 Feat:PostView Page And Components
  client/src/components/Post/PostItem.js
  client/src/components/Post/PostStore.js
  client/src/components/Post/PostViewDetail.js
  client/src/components/Post/PostWriteUp.js
  client/src/components/Post/dummydata.js
  client/src/components/Post/styles.js
  client/src/pages/PostView.js
  client/src/routers/index.js
Labels: Component📦, Feature🙌, FrontEnd🌖, Build Up ⛏, 🐜 Project - α

#499 FEAT:PostWirting 구현 & 알람창설정
  client/src/Assets/spongebob.gif
  client/src/components/Post/PostList.js
  client/src/components/Post/PostViewDetail.js
  client/src/components/Post/styles.js
  client/src/routers/index.js
Labels: ASAP⚡️, Component📦, Feature🙌, FrontEnd🌖, Build Up ⛏, Fix 🛠, 🐜 Project - α

#501 FEAT : WriteUp
  client/src/components/Post/PostList.js
  client/src/components/Post/PostStore.js
  client/src/components/Post/PostWriteUp.js
  client/src/components/Post/styles.js
  client/src/pages/Post.js
  client/src/routers/index.js
Labels: ASAP⚡️, Feature🙌, 도움요청!🤷‍♂️, FrontEnd🌖, Build Up ⛏, Mission Failed 🤦‍♂️, 🐜 Project - α

#502 커멘트 초기 0.1
  client/src/components/Post/Comment/Comment.js
  client/src/components/Post/Comment/CommentStore.js
  client/src/components/Post/Comment/dummydata.js
  client/src/components/Post/Comment/styles.js
  server/controllers/user/sign.js
Labels: FrontEnd🌖, 🐜 Project - α

#503 Feat : Comment C(R-)UD
  client/src/components/Post/Comment/Comment.js
  client/src/components/Post/Comment/CommentList.js
  client/src/components/Post/Comment/CommentStore.js
  client/src/components/Post/Comment/dummydata.js
  client/src/components/Post/Comment/styles.js
Labels: Feature🙌, FrontEnd🌖, 🐜 Project - α

#504 닉네임 중복 막고 댓글부분 조금 수정
  client/src/components/Post/Comment/CommentList.js
  client/src/components/Post/Comment/dummydata.js
  client/src/components/Post/Comment/styles.js
  client/src/components/SignUp/Input.js
Labels: FrontEnd🌖, 🐜 Project - α

#505 FIX : Clean up Components
  client/package-lock.json
  client/package.json
  client/src/components/Post/PostList.js
  client/src/components/Post/PostStore.js
  client/src/components/Post/PostWriteUp.js
  client/src/pages/Post.js
  client/src/routers/index.js
Labels: ASAP⚡️, Component📦, FrontEnd🌖, Fix 🛠, 🐜 Project - α

#508 FEAT : POSTWRITEON 페이지
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/components/Post/PostList.js
  client/src/components/Post/PostViewDetail.js
  client/src/components/Post/PostWriteUpDetail.js
  client/src/components/Post/styles.js
  client/webpack.config.dev.js
Labels: Component📦, Feature🙌, CSS 🎨, Fix 🛠, 🐜 Project - α

#509 Feat : Comment 0.99?
  client/src/components/Post/Comment/Comment.js
  client/src/components/Post/Comment/CommentList.js
  client/src/components/Post/Comment/dummydata.js
  server/controllers/postRequest/post.js
  server/routes/post.js
Labels: FrontEnd🌖, Build Up ⛏, 🐜 Project - α

#511 FEAT:PostViewDetail
  client/src/components/Post/Comment/CommentList.js
  client/src/components/Post/Comment/styles.js
  client/src/components/Post/PostViewDetail.js
  client/src/components/Post/styles.js
Labels: Component📦, Feature🙌, FrontEnd🌖, CSS 🎨, Fix 🛠, 🐜 Project - α

#512 AXIOS 연결 : 근데 501오지게뜸
  client/src/components/Post/PostList.js
  client/src/components/Post/PostWriteUpDetail.js
Labels: ■■■■□, FrontEnd🌖, Fix 🛠, 🐜 Project - α

#513 서버 post POST 요청 에러 해결
  server/controllers/postRequest/post.js
  server/migrations/20220620074718-fk-post.js
  server/models/index.js
Labels: BackEnd🌒, 🐜 Project - α

#514 Token Handler 살짝 수정
  server/controllers/tokenHandler/index.js
Labels: Fix 🛠, 🐜 Project - α

#515 게시글 GET 요청 post/:post_id 삭제 및 post 요청 응답 수정
  server/controllers/postRequest/post.js
  server/routes/post.js
Labels: BackEnd🌒, 🐜 Project - α

#516 FEAT : POST DELETE
  client/src/components/Post/Comment/styles.js
  client/src/components/Post/PostList.js
  client/src/components/Post/PostViewDetail.js
  client/src/components/Post/PostWriteUpDetail.js
  client/src/components/Post/styles.js
Labels: BUG🦠, Feature🙌, 도움요청!🤷‍♂️, FrontEnd🌖, Fix 🛠, Mission Failed 🤦‍♂️, 🐜 Project - α

#518 FEAT : POSTING EDIT
  client/src/components/Post/PostViewDetail.js
  client/src/components/Post/PostWriteUpDetail.js
  client/src/components/Post/styles.js
Labels: BUG🦠, Feature🙌, 도움요청!🤷‍♂️, FrontEnd🌖, Fix 🛠, Mission Failed 🤦‍♂️, 🐜 Project - α

#519 Post view detail 0.6
  client/src/components/Post/PostViewDetail.js
  client/src/components/Post/PostWriteUpDetail.js
  server/controllers/postRequest/post.js
  server/migrations/20220620074141-create-post.js
  server/models/post.js
  server/routes/post.js
Labels: Feature🙌, Mission Complete✌️, FrontEnd🌖, Fix 🛠, 🐜 Project - α

#520 Post view detail 0.6
  client/src/components/Post/PostList.js
  client/src/components/Post/PostViewDetail.js
  server/controllers/postRequest/post.js
Labels: ASAP⚡️, Component📦, Feature🙌, Mission Complete✌️, FrontEnd🌖, Fix 🛠, 🐜 Project - α

#522 FEAT : 수정 시 수정된 글이란 것을 알려주는 문구 표시
  client/src/components/Post/PostViewDetail.js
  client/src/components/Post/PostWriteUpDetail.js
  client/src/components/Post/styles.js
  server/controllers/postRequest/post.js
  server/routes/post.js
Labels: ASAP⚡️, Feature🙌, FrontEnd🌖, Fix 🛠, 🐜 Project - α

#523 Console.log 지우기 & 수정된 글이라는 문구 바로 뜨지 않는것 수정
  client/src/components/Post/Comment/CommentList.js
  client/src/components/Post/PostList.js
  client/src/components/Post/PostViewDetail.js
  client/src/components/Post/dummydata.js
Labels: BUG🦠, ASAP⚡️, FrontEnd🌖, 挑战成功 🐣, Fix 🛠, 🐜 Project - α

#524 url 환경변수화
  client/src/components/MyPage/InfoButton.js
  client/src/components/Post/Comment/CommentList.js
  client/src/components/Post/PostList.js
  client/src/components/Post/PostViewDetail.js
  client/src/components/Post/PostWriteUpDetail.js
  client/src/services/account.js
  client/src/services/comment.js
  client/src/services/diary.js
  client/src/services/sign.js
  client/src/services/trip.js
Labels: Fix 🛠, 🐜 Project - α

#525 fix : post의 trip부분 삭제
  client/src/components/Post/PostViewDetail.js
  server/controllers/postRequest/post.js
  server/migrations/20220620074141-create-post.js
Labels: 🐜 Project - α

#526 시퀄라이즈 trip 삭제 수정
  server/migrations/20220620074718-fk-post.js
  server/models/index.js
  server/models/post.js
Labels: Fix 🛠, 🐜 Project - α

#527 FEAT : SEARCH
  client/src/components/Post/PostList.js
  client/src/components/Post/PostViewDetail.js
Labels: ASAP⚡️, Feature🙌, Mission Complete✌️, FrontEnd🌖, 挑战成功 🐣, 🐜 Project - α

#528 FIX : console지움
  client/src/components/MyPage/InfoButton.js
  client/src/components/Post/Comment/CommentList.js
  client/src/components/Post/PostList.js
  client/src/components/Post/PostViewDetail.js
  client/src/components/Post/PostWriteUpDetail.js
  client/src/components/Post/dummydata.js
  client/src/components/Post/styles.js
  client/src/services/account.js
  client/src/services/comment.js
  client/src/services/diary.js
  client/src/services/sign.js
  client/src/services/trip.js
  server/controllers/postRequest/post.js
  server/migrations/20220620074141-create-post.js
Labels: ASAP⚡️, FrontEnd🌖, Fix 🛠, 🐜 Project - α
